### ISSUE TITLE
False positives

### ISSUE THREAD

**Issue by HatScripts** [OlafenwaMoses/IdenProf#3]
So IdenProf is great at distinguishing say, an image of a police officer from an image of a firefighter.

Out of curiosity I tried getting it to predict the professions of images that do not fall into any of the 10 categories, expecting results with low probability/certainty. Unfortunately this was not the case. It tends to express a high level of certainty even when it shouldn't.

<img src="https://user-images.githubusercontent.com/5691865/52987168-31da6300-344e-11e9-8838-ca9ebc1d7080.jpg" alt="boxer" title="boxer" width="224" height="224">

```
image: test_images\boxer.jpg
waiter  :  99.28185939788818
chef  :  0.4938141442835331
doctor  :  0.13351680245250463
```
<img src="https://user-images.githubusercontent.com/5691865/52987173-39017100-344e-11e9-8c76-9cc85c49d1fd.jpg" alt="cyclist" title="cyclist" width="224" height="224">

```
image: test_images\cyclist.jpg
police  :  95.38164734840393
mechanic  :  3.639966994524002
farmer  :  0.9620786644518375
```
<img src="https://user-images.githubusercontent.com/5691865/52987183-3ef75200-344e-11e9-835c-fcba82cf97c4.jpg" alt="film_critic" title="film_critic" width="224" height="224">

```
image: test_images\film_critic.jpg
firefighter  :  96.90539836883545
mechanic  :  2.035141922533512
judge  :  0.8867966011166573
```
<img src="https://user-images.githubusercontent.com/5691865/52987265-8978ce80-344e-11e9-8fc3-320f603a5546.jpg" alt="food_critic" title="food_critic" width="224" height="224">

```
image: test_images\food_critic.jpg
judge  :  64.44069743156433
waiter  :  31.9767564535141
chef  :  3.5824909806251526
```
<img src="https://user-images.githubusercontent.com/5691865/52987210-58000300-344e-11e9-9247-39f09f95f7f5.jpg" alt="person" title="person" width="224" height="224">

```
image: test_images\person.jpg
pilot  :  82.74794816970825
doctor  :  16.624705493450165
judge  :  0.6167999934405088
```
<img src="https://user-images.githubusercontent.com/5691865/52987276-91d10980-344e-11e9-8bdf-d0c66704e226.jpg" alt="person2" title="person2" width="224" height="224">

```
image: test_images\person2.jpg
waiter  :  55.20762801170349
judge  :  43.84030997753143
doctor  :  0.8999278768897057
```
<img src="https://user-images.githubusercontent.com/5691865/52987284-95649080-344e-11e9-8d02-e3b9e8687253.jpg" alt="person3" title="person3" width="224" height="224">

```
image: test_images\person3.jpg
judge  :  99.99868869781494
waiter  :  0.0009612601388653275
farmer  :  0.00032320690479537006
```
<img src="https://user-images.githubusercontent.com/5691865/52987288-98f81780-344e-11e9-99a2-b7eb018e8f91.jpg" alt="person4" title="person4" width="224" height="224">

```
image: test_images\person4.jpg
pilot  :  96.692955493927
police  :  2.24935095757246
farmer  :  0.48480830155313015
```
<img src="https://user-images.githubusercontent.com/5691865/52987293-9bf30800-344e-11e9-84af-f477e0d61e16.jpg" alt="person5" title="person5" width="224" height="224">

```
image: test_images\person5.jpg
pilot  :  98.77968430519104
judge  :  0.4517796915024519
police  :  0.375298666767776
```
<img src="https://user-images.githubusercontent.com/5691865/52987295-9f868f00-344e-11e9-9c75-3792fc9ba988.jpg" alt="person6" title="person6" width="224" height="224">

```
image: test_images\person6.jpg
pilot  :  99.83604550361633
engineer  :  0.15157574089244008
doctor  :  0.006174622831167653
```
<img src="https://user-images.githubusercontent.com/5691865/52987321-b927d680-344e-11e9-95bf-eceb11b31d6a.jpg" alt="person7" title="person7" width="224" height="224">

```
image: test_images\person7.jpg
mechanic  :  56.29146695137024
farmer  :  35.54711639881134
pilot  :  6.040527299046516
```
<img src="https://user-images.githubusercontent.com/5691865/52987325-bf1db780-344e-11e9-91b3-5a621b687b55.jpg" alt="photographer" title="photographer" width="224" height="224">

```
image: test_images\photographer.jpg
doctor  :  87.44643330574036
police  :  12.040632963180542
waiter  :  0.23560849949717522
```
<img src="https://user-images.githubusercontent.com/5691865/52987326-c3e26b80-344e-11e9-9572-c55013d428a0.jpg" alt="photographer2" title="photographer2" width="224" height="224">

```
image: test_images\photographer2.jpg
waiter  :  64.6943986415863
doctor  :  22.024451196193695
pilot  :  6.768552213907242
```
<img src="https://user-images.githubusercontent.com/5691865/52987333-c93fb600-344e-11e9-8d71-9666d6252941.jpg" alt="programmer" title="programmer" width="224" height="224">

```
image: test_images\programmer.jpg
police  :  72.09265232086182
mechanic  :  25.71178674697876
judge  :  1.56310573220253
```
<img src="https://user-images.githubusercontent.com/5691865/52987344-d0ff5a80-344e-11e9-9c85-7a2bc4213289.jpg" alt="stripper" title="stripper" width="224" height="224">

```
image: test_images\stripper.jpg
judge  :  86.99167370796204
waiter  :  12.583789229393005
mechanic  :  0.265811407007277
```
<img src="https://user-images.githubusercontent.com/5691865/52987349-d65ca500-344e-11e9-826f-5137cd6cd685.jpg" alt="writer" title="writer" width="224" height="224">

```
image: test_images\writer.jpg
doctor  :  99.8594343662262
waiter  :  0.13804479967802763
mechanic  :  0.0012477327800297644
```

What could be done to resolve this? Perhaps an `other` category, with the training data populated by images of "generic" people (or famous, but wearing regular clothing)?

**Comment by jcharleston** [comment]
I'm curious, did you find a solution?

Joe

**Comment by OlafenwaMoses** [comment]
The IdenProf model will classify images only the categories provided in the training dataset. To recognize the other categories, they will have to be included in the training dataset. It is a 10-class classification model, not a universal model.

**Comment by HatScripts** [comment]
> The IdenProf model will classify images only the categories provided in the training dataset. To recognize the other categories, they will have to be included in the training dataset. It is a 10-class classification model, not a universal model.

I think you maybe misunderstood. I wasn't expecting it to classify images outside of the 10 categories that it's been trained on. Of course, I'm not expecting the NN to perform magic. I was just expecting it to tell me when an image probably _doesn't_ fall within any of the 10 categories.

Currently it's like it's answering the question "If you **_had_** to classify this image as one of these 10 categories, which would you choose?" The AI should be able to give "None of the above" as an answer.

That is to say, this:
<img src="https://user-images.githubusercontent.com/5691865/52987168-31da6300-344e-11e9-8838-ca9ebc1d7080.jpg" alt="boxer" title="boxer" width="224" height="224">

```
image: test_images\boxer.jpg
waiter  :  99.28185939788818
chef  :  0.4938141442835331
doctor  :  0.13351680245250463
```

Should give an output that looks more like this:
```
image: test_images\boxer.jpg
waiter  :  0.2951950312615013
chef  :  0.1597396731017543
doctor  :  0.0917562837653921
```
